### PR TITLE
Bump Kubernetes to v1.14.4

### LINKED ISSUE #55: Bump Kubernetes version to v1.14.4
Release [Kubernetes v1.14.4](https://github.com/kubernetes/kubernetes/releases/tag/v1.14.4) is the latest and current version in KTRW should be bumped (v1.14.1).

### PR DESCRIPTION
**Pull request by amimof**
All components are updated which includes:
* kube-apiserver
* kube-scheduler
* kube-controller-manager
* kube-proxy
* kubelet
* kubectl (for testing only)

Fixes #55

### CODE REVIEW

**Comment by amimof** [comment]
@anton-johansson I just wanted to let you know that I upgraded my existing cluster from `1.14.1 -> 1.14.4` using `serial_all=1` and it worked perfectly!

**Comment by anton-johansson** [comment]
Awesome! I'll also give it a go within a few weeks too.

When this PR is merged, what are the plans for `v1.15.0`? It was released about a month ago.

**Comment by amimof** [comment]
Having 1.15.0 is as easy as easy as any other minor release. I guess I need to go through the [CHANGELOG-15.md](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md) and see if there are any obvious breaking changes. You are welcome to test it out as well.

**Comment by anton-johansson** [comment]
Yeah, I've taken a quick look at the changelog and I couldn't find anything breaking. I couldn't find anything that I need either, but it's nice to be up to date. :)

I can test it later in the summer, or after it, if you don't want or have time. But do you know where I can find information about compatible versions of etcd, containerd, cni, and so on? How do you know when things needs to be updated?

**Pull request merged**
