### PR TITLE
Allow specifying `--enable-admission-plugins`

### LINKED ISSUE #31: Pod security policies
I started messing around with pod security policies to easily notice if my containers are running as root (and doing more complex rules of course). I couldn't get it working, and I ended up in this issue: kubernetes/kubernetes#53063

The argument value for `--enable-admission-plugins` is hardcoded in KTRW. What about having it as an Ansible setting, with a default value matching the currently hardcoded value?

Note: I haven't tested if this actually works for me yet, I just stumbled across it. What's your take on this?

### PR DESCRIPTION
**Pull request by anton-johansson**
This is necessary if you want to enable other admission plugins, such as the `PodSecurityPolicy` plugin.

Closes #31

### CODE REVIEW

**Comment by anton-johansson** [comment]
Hmm, the README looks a bit stupid with this change:
https://github.com/anton-johansson/kubernetes-the-right-way/tree/31-allow-specifying-admission-plugins

Suggestions?

**Comment by amimof** [comment]
The documentation for `kube-apiserver` states that the flag `--enable-admission-plugins` will enable plugins in **addition** of the default ones which are:
```
NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority
```
I've tested the following in the service unit file and the sure enough, those default plugins are enabled without me having to specify them. Which means that the README should state `NodeRestriction` as the default value since that is the only non-default which is enabled.

**Comment by anton-johansson** [comment]
Awesome, I'll fix that!

**Comment by anton-johansson** [comment]
@amimof: I've changed default to `Initializers,NodeRestriction` as it seems like both of them is in KTRW but aren't default in `kube-apiserver`.

However, two things regarding your comments:
* Shouldn't we default to no additional plugins in KTRW? Or is it something KTRW-related in `Initializers` or `NodeRestriction`? It feels more natural if the default would be no plugins.
* You mentioned in #31 that it would be nice if you could override **any** command line argument to `kube-apiserver`. Do you have any ideas for how that should work? Or should we do that outside of this PR? (I'd gladly do that, I'm in need of `PodSecurityPolicy` :smile:)

**Comment by amimof** [comment]
Looks like `Initializers` is an Alpha feature and not necessarily used here. Think it's safe to remove. As for `NodeRestriction`, it enables us to authenticate and authorize kubelets using using x509 certificates. All though I'm not 100% sure of this.

**Comment by amimof** [comment]
Ok, so i tested an install without `--enable-admission-plugins` and seems to be working nicely. So if possible we should remove that from the `kube-apiserver.service.j2` template as well as `Initializers`.

**Comment by anton-johansson** [comment]
Ok, great! I've updated it to not add any admission plugins by default.

**Comment by amimof** [comment]
Awesome, but can we have underscores instead? :)

**Comment by anton-johansson** [comment]
Woups, of course it should be underscores. Fixed, and added qoutes!

**Comment by anton-johansson** [comment]
Not quite sure why the Travis build fails. Ideas?

**Comment by amimof** [comment]
So it turns out that kube-apiserver doesn't like quotes and spaces in the value to `--enable-admission-plugins`. So the flag should only be added to the unit file if the variable is defined. Otherwise it is omitted. I pushed the changes to your branch.

**Comment by anton-johansson** [comment]
Allright, makes sense. Change looks good!

**Pull request merged**
